#ifndef DOP-MII
#define DOP-Mii

#include "dopmii/Global.h"
#include "dopmii/Boot2.h"
#include "dopmii/ChannelMatrix.h"
#include "dopmii/Boot2.h"
#include "dopmii/Controller.h"
#include "dopmii/DiscLight.h"
#include "dopmii/Error.h"
#include "dopmii/Filesystem.h"
#include "dopmii/Gecko.h"
#include "dopmii/Http.h"
#include "dopmii/Identify.h"
#include "dopmii/IOSMatrix.h"
#include "dopmii/Nand.h"
#include "dopmii/Network.h"
#include "dopmii/Nus.h"
#include "dopmii/Patcher.h"
#include "dopmii/rjindael.h"
#include "dopmii/RuntimeIOSPatch.h"
#include "dopmii/Scripting.h"
#include "dopmii/Settings.h"
#include "dopmii/sha1.h"
#include "dopmii/SysCheck.h"
#include "dopmii/sysconf.h"
#include "dopmii/SysMenuMatrix.h"
#include "dopmii/System.h"
#include "dopmii/SysTitle.h"
#include "dopmii/Title.h"
#include "dopmii/TmdView.h"
#include "dopmii/Tools.h"
#include "dopmii/UsbStorage.h"
#include "dopmii/Video.h"
#include "dopmii/Wad.h"
#include "dopmii/WiiMote.h"

#endif